### ISSUE TITLE
User feedback (andreagighi)

### ISSUE THREAD

**Issue by x1nixmzeng** [x1nixmzeng/rzfswizard#2]
(see http://forum.ragezone.com/f697/raiderz-filesystem-wizard-msf-packer-859693/#post7141814)

> Ok i've done a lot of test... tools are great ! I've already added lot of contents on client by simply modify existing files... but what really miss now is the insert function to add new files in the packs.

> P.S.: ...normally when i work on client i use the full unpacked client into a dump folder and i modify variouse files here... what is annoiyng is select files one by one to apply patch... (m8be generate new fileindex and new pack by folder can be easyer for all?)

**Comment by Reor** [comment]
@x1nixmzeng Hello sir,
We are actually at a game development (RaiderZ),We have a client and have the .mrf files unpacked and could edit the client.The unpacket used a fileindex.msf that the unpacked source is available . Now we want the folder back to .mrf files basicly pack NA Client :)

Of course, will be paid for it. We hope you can  create one and currently we can not go on without this packer...

Skype: skysoulblade

~

**Comment by x1nixmzeng** [comment]
Hey @Reor.

I'm no longer interested in RaiderZ, sorry!

If you can unpack the NA client, I suggest writing a different filesystem for your server.
